name: Production

on:
  push:
    branches: ["main"]

jobs:
  Deploy-Infrastructure-Terragrunt:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout Repository
        uses: "actions/checkout@v3"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Terragrunt Apply
        run: |
          docker run --rm -i  \
          --name "terraform" \
          --user "$(id -u):$(id -g)" \
          -v $PWD:/app \
          -e "TERRAGRUNT_DOWNLOAD=/app/infrastructure/environments/$ENVIRONMENT/.terragrunt-cache" \
          -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
          -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
          -e "AWS_REGION=$AWS_REGION" \
          -w "/app/infrastructure/environments/$ENVIRONMENT" \
          ghcr.io/antocapp/terraform:latest \
          apply -auto-approve